/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const TictactoeRoomidLazyImport = createFileRoute('/tictactoe/$roomid')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const TictactoeRoomidLazyRoute = TictactoeRoomidLazyImport.update({
  path: '/tictactoe/$roomid',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/tictactoe.$roomid.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/tictactoe/$roomid': {
      id: '/tictactoe/$roomid'
      path: '/tictactoe/$roomid'
      fullPath: '/tictactoe/$roomid'
      preLoaderRoute: typeof TictactoeRoomidLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  TictactoeRoomidLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/tictactoe/$roomid"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/tictactoe/$roomid": {
      "filePath": "tictactoe.$roomid.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
